name: Commit the dist folder
on: [push, workflow_dispatch]
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          npm i
          npm run-script build
          git config --global user.email "just4now666666@gmail.com"
          git config --global user.name "donno2048"
          git commit -am "${GITHUB_WORKFLOW,,}" || true
          git push
