name: Update package-lock
on: workflow_dispatch
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      - uses: EndBug/add-and-commit@v7.2.1
        with:
          author_name: donno2048
          author_email: just4now666666@gmail.com
          message: 'Update package-lock'
